#!/bin/bash

NUM_THREADS=10000;
TRIALS=25;
METHODS=3;

# Rebuild
make clean;
make NUM_THREADS=$NUM_THREADS;

# Remove all previous data
rm -rf data/*

# Print out TRIALS data sets for each method
mkdir -p data;
for i in `seq 1 $TRIALS`; 
do 
echo;
echo "Trial $i";

for j in `seq 1 $METHODS`;
do
    ./Lab2 $j; 
    cat method_$j.json > data/${j}_${i}.json; 
    rm -f method_$j.json;
done
done

cd data;

# Keep raw data
mkdir -p traces
cp ./* ./traces/ 2>/dev/null

# Move end of method x to right after beginning of method x
for i in `seq 1 $TRIALS`; 
do 
for j in `seq 1 $METHODS`;
do
    { printf "$((2*NUM_THREADS+5))m4\n,p\n" | ed -s ${j}_${i}.json | sponge ${j}_${i}.json; } 2>/dev/null
done
done

# Extract the time differences
for i in `seq 1 $TRIALS`;
do  
for j in `seq 1 $METHODS`;
do
    jq .[].ts ${j}_${i}.json | awk 'ORS=NR%2?" ":"\n"' | awk '{print $2-$1}' | sponge ${j}_${i}.json; 
done
done

# Average out thread length
for i in `seq 1 $TRIALS`;
do
for j in `seq 1 $METHODS`;
do
    # Initialization time, Method total time
    head -2 ${j}_${i}.json >> temp_$j;
    
    # Active thread duration mean
    tail -n+3 ${j}_${i}.json | head -n-1 | awk '{s+=$1}END{print s/NR}' >> temp_$j;
    
    # Active thread duration standard deviation
    tail -n+3 ${j}_${i}.json | head -n-1 | awk '{x+=$0;y+=$0^2}END{print sqrt(y/NR-(x/NR)^2)}' >> temp_$j;
    
    # Thread destruction time
    tail -1 ${j}_${i}.json >> temp_$j;
    
    # Overwrite Original Files
    cat temp_$j > ${j}_${i}.json
    rm -f temp_$j
done
done

# Get mean and standard deviations of methods
for j in `seq 1 $METHODS`;
do
> results_$j;
    for i in `seq 1 $TRIALS`;
    do
        paste ${j}_${i}.json results_$j | column -t | sponge results_$j;
    done
    awk '{x=0; y=0; for(i=1; i<=NF; i++){x+=$i;y+=$i^2}; print x/NF " " sqrt(y/NF-(x/NF)^2) }' results_$j | tr '\n' ' ' | sponge Results_$j;
done

# Summarize results
echo -e "$TRIALS Trials executed with $NUM_THREADS threads.\n\n" > Summary.txt
for j in `seq 1 $METHODS`;
do
      echo "Method $j" >> Summary.txt;
      awk '{ printf "\tInitialisation:\n";
      printf "\t\tMean: %i µs\n", $1;
      printf "\t\tStandard Deviation: %i µs\n", $2;
       
      printf "\tTotal Length of Method:\n";
      printf "\t\tMean: %i µs\n", $3;
      printf "\t\tStandard Deviation: %i µs\n", $4;
       
      printf "\tActive Thread Length:\n";
      printf "\t\tMean: %.2f µs\n", $5;
      printf "\t\tStandard Deviation: %.2f µs\n", $8;
       
      printf "\tThread Destruction:\n";
      printf "\t\tMean: %i µs\n", $9;
      printf "\t\tStandard Deviation: %i µs\n", $10;
     }' Results_$j >> Summary.txt;
     echo >> Summary.txt;
    rm -f Results_$j
done

# Clean up
rm -r *.json
for j in `seq 1 $METHODS`;
do
    echo -e "Initialisation:\nTotal_Length:\nThread_Length_Average:\nThread_Length_Standard_Deviation:\nThread_Destruction:" > temp; paste temp results_$j | column -t | sponge results_$j; rm -rf temp
done

cd ..