# Declaration of variables
CC = g++
CC_FLAGS = -std=c++11 -pthread

# Make
main: main.cpp tracelib.h
	$(CC) $(CC_FLAGS) main.cpp tracelib.h -o Lab2
 
# Clean
clean:
	rm -f Lab2 method_1.json method_2.json method_3.json